name: RepSpark → Sheets

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Run worker
        env:
          REPSPARK_URL: https://app.repspark.com/_511
          REPSPARK_EMAIL: ${{ secrets.REPSPARK_EMAIL }}
          REPSPARK_PASSWORD: ${{ secrets.REPSPARK_PASSWORD }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GSHEET_TAB: BASE
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
          PRODUCTS_XPATH: "/html/body/div[2]/div[1]/div/div[1]/div[2]/div[2]/div/ul/li[1]/a"
          EXPORT_BTN_ID_XPATH: "//*[@id='ctl00_ctl00_cphB_filterMenu_btnExportToExcelFull']"
          EXPORT_FALLBACK_XPATH: "/html/body/form/div[3]/div[1]/div[3]/div[1]/div/nav/div/div[2]/div/a/span"
        run: python repspark_worker.py

          - name: Upload debug artifacts
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: repspark-debug
      path: |
        downloads/**
        debug_*.png
